### PR TITLE
Provide capability to skip creating cluster-wide resources

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

Provide the capability to skip creating cluster-wide resources in case the Helm chart is already created in another namespace.

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@krottiers Pipeline is failing because they've introduced a naming convention for roles recently.
Shall I update it in this minor version or go straight to 1.0? Not sure if people use it so might be able to justify it.

**Comment by krottiers** [comment]
> @krottiers Pipeline is failing because they've introduced a naming convention for roles recently.
> Shall I update it in this minor version (less ideal) or go straight to 1.0 (ideal)? Not sure if people use it so might be able to justify it.
> 
> Alternative is to ignore the failure and handle it later on. (less ideal)

So if I understand correctly the Azure Devops requires a certain naming for the roles?

**Comment by krottiers** [comment]
@tomkerkhove Straight to 1.0 is ok for me

**Review by krottiers — APPROVED** [review]

**Comment by tomkerkhove** [comment]
I'll do it in a seperate!

**Pull request merged**
